### ISSUE TITLE
Core functionality

### ISSUE THREAD

**Issue by RAJAGOPALAN-GANGADHARAN** [RAJAGOPALAN-GANGADHARAN/DConsole#1]
The main objective of this module is to pipe outputs from stderr and stdout into the app, while this is fairly easy in linux, windows needs a long hack.

So the objective is to create a core functionality that will pipe the streams outputs separately at a binary level (Not language level i.e. no code injection or replacing streams). The UI part is a separate module.

Subtasks 

Windows

- [x] Find a way to pipe stderr and stdout in realtime ( Try using screen buffer rather than pipes ) (Difficult:15)

Linux

- [x] Launch application with flags that redirect data to sockets (Difficult:15)

Common

- [x] Same format that will be handled in UI part for displaying (Intermediate:10)

- [x] Signals and support/Callback functions (Intermediate:10)

**Comment by subhangi2731** [comment]
can you please assign this issue to me? @RAJAGOPALAN-GANGADHARAN

**Comment by RAJAGOPALAN-GANGADHARAN** [comment]
Subtasks 

Windows

- [ ] Find a way to pipe stderr and stdout in realtime ( Try using screen buffer rather than pipes )

Linux

- [ ] Launch application with flags that redirect data to sockets

Common

- [ ] Same format that will be handled in UI part for displaying

- [ ] Signals and support/Callback functions
