### ISSUE TITLE
Move everything from unix to linux

### ISSUE THREAD

**Issue by RAJAGOPALAN-GANGADHARAN** [RAJAGOPALAN-GANGADHARAN/DConsole#15]
The code was written in the assumption that unix codebase will be common to both mac and linux, But it proved to be difficult than expected. Hence move all the files from unix directory to linux directory. Verify that it compiles by making appropriate changes in CMakeLists.txt

**Comment by hari-krishnan-88** [comment]
Hey @RAJAGOPALAN-GANGADHARAN  can i contribute to this issue. I am a beginner and would love to understand this issue. Can u please explain what i should do? Thank YOU.

**Comment by RAJAGOPALAN-GANGADHARAN** [comment]
@hari-krishnan-88 this is a bit outdated issue, I've been meaning to close this as there were some architecture changes rendering this useless. If you prefer javascript you could work on UI part, Thanks!
