### ISSUE TITLE
addition of issue, pr templates, welcome bot and greeting bots

### ISSUE THREAD

**Issue by Sloth-Panda** [RAJAGOPALAN-GANGADHARAN/DConsole#23]
would like to add these to your project. let me know if you want them and assign too.

welcome bot config file will be  having a proper message that will show up when any user will open up an issue or pull-request for the first time.
For reference, check out and download the bot in your repo from the below link 👇

https://github.com/apps/welcome

**Comment by RAJAGOPALAN-GANGADHARAN** [comment]
Sure go ahead

**Comment by Sloth-Panda** [comment]
@RAJAGOPALAN-GANGADHARAN

**Comment by Sloth-Panda** [comment]
can you please check this @RAJAGOPALAN-GANGADHARAN

**Comment by RAJAGOPALAN-GANGADHARAN** [comment]
Can you address the comment i left in your pr?

**Comment by Sloth-Panda** [comment]
@RAJAGOPALAN-GANGADHARAN  can you tell me you want those lines to go one below the other or just a new line in between without breaking?
