### ISSUE TITLE
addition of code of conduct and contributing file

### ISSUE THREAD

**Issue by Sloth-Panda** [RAJAGOPALAN-GANGADHARAN/DConsole#25]
This project lacks a code of conduct and contributing file so would like to add them Let me know

**Comment by Akash20x** [comment]
Can you please assign me this issue as a part of Cross Woc. I would be very happy to do it

**Comment by RAJAGOPALAN-GANGADHARAN** [comment]
Hey I appreciate your enthusiasm but I think it's unnecessary :)

But feel free to browse other issues. Thanks!
