### ISSUE TITLE
Adding space indentation

### ISSUE THREAD

**Issue by Diksha-11** [RAJAGOPALAN-GANGADHARAN/DConsole#28]
## 💥 I would like to add space indentation to the /Source/main.cpp of Dconsole.
I request @RAJAGOPALAN-GANGADHARAN sir to assign me this issue so that main.cpp will seem more readable.

**Comment by RAJAGOPALAN-GANGADHARAN** [comment]
The core logic is changed to http and will be written in go. So this is no longer a valid issue! Feel free to browse other issues.
