### ISSUE TITLE
Addition of Contributors.md file 

### ISSUE THREAD

**Issue by Ayonijakaushik19** [RAJAGOPALAN-GANGADHARAN/DConsole#29]

**Comment by Ayonijakaushik19** [comment]
Hi @RAJAGOPALAN-GANGADHARAN, Please assign this to me. I would love to do it.

**Comment by RAJAGOPALAN-GANGADHARAN** [comment]
Hey I appreciate your enthusiasm but I think it's unnecessary :)

But feel free to browse other issues. Thanks!
