### ISSUE TITLE
Add Pull Request template

### ISSUE THREAD

**Issue by pushkar2112** [RAJAGOPALAN-GANGADHARAN/DConsole#32]
The project does not have a Pull Request template.

**Comment by pushkar2112** [comment]
I would like to resolve this.

**Comment by RAJAGOPALAN-GANGADHARAN** [comment]
@pushkar2112 , thank you for the initiative but someone else has already done it - https://github.com/RAJAGOPALAN-GANGADHARAN/DConsole/issues/8

**Comment by pushkar2112** [comment]
The templates are not there in your default branch and while raising a new you cannot see any template appearing there

**Comment by RAJAGOPALAN-GANGADHARAN** [comment]
@pushkar2112 I see, must have missed it during rebase but I think I don't want to enforce some kind of pattern to follow so this idea doesn't excite me. Hope you understand, I request to try out other issues Thanks!
