### ISSUE TITLE
Add CONTRIBUTING.md

### ISSUE THREAD

**Issue by atarax665** [RAJAGOPALAN-GANGADHARAN/DConsole#4]
### Add ```CONTRIBUTING.md``` File

As this project is a part of an Open Source Program ```NJACK Winter of Code``` I would recommend to have a contribution guidelines file (```CONTRIBUTING.md```) to assist beginners to get started with open source contribution.

Points to be covered in the guideline :
- How to pull your first request.
- How to create issue.
- Some general rules to keep in mind while contributing to an open source project.
- Links of some tutorials which will help beginners to learn the basics of git and github.

**Comment by anishkabhatia** [comment]
Can I take this up?

**Comment by atarax665** [comment]
> Can I take this up?

@anishkabhatia Sorry, but I am looking to take this issue.

**Comment by atarax665** [comment]
@RAJAGOPALAN-GANGADHARAN Can you please add the required labels and assign this to me?

**Comment by RAJAGOPALAN-GANGADHARAN** [comment]
Im assigning @atarax665.
