### ISSUE TITLE
Readme Updation and Code of Conduct

### ISSUE THREAD

**Issue by Tejas1510** [RAJAGOPALAN-GANGADHARAN/DConsole#6]
Currently, the readme is not having a getting started guide so a beginner will find it difficult to contribute to the project.
Also, I wish to add badges which will keep real-time track of pull request opened, closed, issues open and closed so it will use for you to manage
So can I go for it @RAJAGOPALAN-GANGADHARAN 

Also The project is currently missing the Code of Conduct file which is important for open source project
So can I go for it

**Comment by RAJAGOPALAN-GANGADHARAN** [comment]
Sure

**Comment by Tejas1510** [comment]
@RAJAGOPALAN-GANGADHARAN can you then assign me and add appropriate label
